package:
  name: khiops-driver-gcs
  version: 0.0.1

source:
  path: ../

build:
  number: 0
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}

files:
  - lib/libkhiopsdriver_file_gcs.so*

about:
  home: https://khiops.org
  license: BSD+3-clause
  summary: Khiops driver to access files on Google Cloud Storage
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiops
