{% set version = os.environ.get('GCS_DRIVER_VERSION').replace("-", "") %}

package:
  name: khiops-driver-gcs
  version: {{ version }}

source:
  path: ../

build:
  number: 0
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - libcurl
    #- libgoogle-cloud-all-devel
    - libgoogle-cloud-storage-devel
    #- libboost
    - libboost-devel
    - libboost-headers
    #- libboost-python
    #- libboost-python-devel
  run:
    - fmt
    - spdlog
    #- libgoogle-cloud-cpp
    - libgoogle-cloud-storage

files:
  - lib/libkhiopsdriver_file_gcs.so* [linux]
  - lib/libkhiopsdriver_file_gcs*.dylib [osx]
  - lib/*.dll [win]
  - bin/*.dll [win]

about:
  home: https://khiops.org
  license: BSD+3-clause
  summary: Khiops driver to access files on Google Cloud Storage
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiopsdriver_gcs
