{% set version = os.environ.get('GCS_DRIVER_VERSION').replace("-", "") %}

package:
  name: khiops-driver-gcs
  version: {{ version }}

source:
  path: ../

build:
  number: 0
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - conda-forge::curl-devel
    - conda-forge::libgoogle-cloud-all-devel
    - conda-forge::libboost
    - conda-forge::libboost-devel
    - conda-forge::libboost-headers
    - conda-forge::libboost-python
    - conda-forge::libboost-python-devel
  run:
    - conda-forge::fmt
    - conda-forge::spdlog
    - conda-forge::google-cloud-cpp
    - conda-forge::libgoogle-cloud-all

files:
  - lib/libkhiopsdriver_file_gcs.so* [linux]
  - lib/libkhiopsdriver_file_gcs*.dylib [osx]
  - lib/*.dll [win]
  - bin/*.dll [win]

about:
  home: https://khiops.org
  license: BSD+3-clause
  summary: Khiops driver to access files on Google Cloud Storage
  doc_url: https://khiops.org
  dev_url: https://github.com/khiopsml/khiopsdriver_gcs
