#ifndef OAUTH2_TOKEN_MANAGER_H
#define OAUTH2_TOKEN_MANAGER_H

#include <google/cloud/credentials.h>

/**
 * @brief Manages OAuth2 tokens for Google Cloud Storage authentication.
 *
 * This class loads OAuth2 tokens from a JSON file (as generated by Python),
 * checks for token expiration, and refreshes tokens when needed.
 */
class OAuth2TokenManager {
public:
  /**
   * @brief Construct a new OAuth2TokenManager
   *
   * @param token_file_path Path to the JSON file containing OAuth2 tokens
   */
  explicit OAuth2TokenManager(const std::string &token_file_path, const std::string &certificate_path = "");

  /**
   * @brief Get the current access token, refreshing if necessary
   *
   * @return std::string The access token
   */
  std::string GetAccessToken();

  /**
   * @brief Create Google Cloud credentials using the current access token
   *
   * @return std::shared_ptr<google::cloud::Credentials> The credentials object
   */
  std::shared_ptr<google::cloud::Credentials> MakeCredentials();

private:
  std::string token_file_path_;
  std::string certificate_path_;
  std::string access_token_;
  std::string refresh_token_;
  std::string token_uri_;
  std::string client_id_;
  std::string client_secret_;
  std::chrono::system_clock::time_point token_expiry_;

  /**
   * @brief Load token data from the JSON file
   */
  void LoadTokenData();

  /**
   * @brief Check if the current token is expired or about to expire
   *
   * @return true if the token is expired or will expire soon
   * @return false if the token is still valid
   */
  bool IsTokenExpired();

  /**
   * @brief Refresh the access token using the refresh token
   */
  void RefreshAccessToken();

  /**
   * @brief Update the token file with new token information
   *
   * @param expires_in Token expiration time in seconds
   */
  void UpdateTokenFile(int expires_in);
};

#endif // OAUTH2_TOKEN_MANAGER_H
