---
name: Source package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Create source archive
        run: |
          scripts/git-archive-all.sh --format tar.gz khiops-driver-gcs.tar.gz 
      - name: Upload packages to the release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: '*.tar.gz'
          body: |
            **This release is for testing purposes only and there is no support for it.**
            **Go to https://khiops.org to install the latest supported version.**
          draft: false
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true
